name: Publish to Nuget

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION} --no-restore
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build --verbosity normal
    - name: Pack Abstractions
      run: dotnet pack src/Marquitos.AspNetCore.Components.JSInterop --configuration Release /p:Version=${VERSION} --no-build --output ./Publish
    - name: Pack RabbitMQ
      run: dotnet pack src/Marquitos.AspNetCore.Components --configuration Release /p:Version=${VERSION} --no-build --output ./Publish
    - name: Publish to Nuget
      run: dotnet nuget push Publish/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN} --skip-duplicate
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_API_KEY }}
